/* ==========================================================================
 * Acceptance test for the SH2 memory timing model (32x-playground
 * pico/32x/vrd_timing.c).
 *
 * A timing model that has not been checked against arithmetic computed
 * independently of it is not a measurement, it is a second opinion from the
 * same source.  This cartridge exists so the model can be falsified: it makes
 * a known number of accesses of exactly one kind, so the wait cycles the model
 * should charge follow directly from the manual and can be compared with what
 * it did charge.
 *
 * One kind per build, selected by TIMING_PHASE, because a composite loop turns
 * a disagreement into an ambiguity -- you learn that something is wrong but
 * not which term.
 *
 *   0  cache-through SDRAM longword reads    docs 32x :890, :897
 *   1  frame buffer word writes              docs 32x 4.1
 *   2  cache-through cartridge ROM longword reads
 *
 * Loop code and the loop counter live in cached SDRAM and are touched every
 * iteration, so they settle into the cache and contribute hits at zero cost.
 * The uncached tally should therefore equal the access count exactly, which is
 * itself part of what is being checked.
 *
 * Completion is signalled in SDRAM rather than a comm register: PicoDrive's
 * debug read does not serve the $A151xx range (KNOWN_ISSUES).
 * ========================================================================== */

/* Generated by the Makefile so that changing either value actually rebuilds
 * this object -- the compiler flags alone are not a dependency the build can
 * see, which is exactly how the first run of this test silently measured the
 * previous phase. */
#include "timing_config.h"

/* The counters run from power-on and the startup COMM_MOK poll spin is
 * cache-through, so a single run buries the signal in ~221,000 uncached
 * accesses of boot noise. Two builds differing only in TIMING_ITERS, compared
 * by slope, cancel every fixed cost exactly -- the same technique the 68000 LZ
 * probe uses against frame-count overhead. */

/* 16 KB of scratch, addressed through both aliases.  Taking the address of a
 * real object rather than naming 0x06000000 keeps this clear of the image. */
static volatile unsigned long timing_scratch[4096];

volatile unsigned long sh2_timing_done;
volatile unsigned long sh2_timing_iters;
volatile unsigned long sh2_timing_phase;

void sh2_timing_test(void)
{
    unsigned int i;

    sh2_timing_phase = TIMING_PHASE;
    sh2_timing_iters = TIMING_ITERS;
    sh2_timing_done  = 0;

#if TIMING_PHASE == 0
    {
        /* 0x20000000 turns the cached alias into the cache-through one
         * (sh7604 8.3).  Manual :897: the read is still an 8-word burst. */
        volatile unsigned long *p = (volatile unsigned long *)
            ((unsigned long)timing_scratch | 0x20000000u);
        unsigned long sink = 0;
        for (i = 0u; i < TIMING_ITERS; i++)
            sink += p[i & 1023u];
        timing_scratch[0] = sink;
    }
#elif TIMING_PHASE == 1
    {
        /* Word writes: a byte write to the frame buffer cannot store zero,
         * and the pixel area starts past the 256-word line table. */
        volatile unsigned short *fb =
            (volatile unsigned short *)0x24000000u;
        for (i = 0u; i < TIMING_ITERS; i++)
            fb[256u + (i & 1023u)] = (unsigned short)(i | 0x0101u);
    }
#else
    {
        volatile const unsigned long *rom =
            (volatile const unsigned long *)0x22000000u;
        unsigned long sink = 0;
        for (i = 0u; i < TIMING_ITERS; i++)
            sink += rom[i & 1023u];
        timing_scratch[0] = sink;
    }
#endif

    sh2_timing_done = 0x7D07E;          /* "done" */
    for (;;) { }
}
