#!/usr/bin/env python3
"""Extract the Sega 32X initial program / security block from a retail cartridge.

The block at cartridge $0003F0 is Sega copyright, so it is not stored in this
repository.  It is lifted at build time from a retail 32X ROM the user supplies.

docs/32x-hardware-manual.md section 5.2:

    "The Initial program must begin from the start of the program (address
     3F0h) without change.  The Boot ROM built into 32X confirms that the
     Initial program is provided here.  When contents do not match, 32X becomes
     locked and access cannot be done from the Mega Drive side."

So the block is copied byte for byte and never patched.  It ends with a
cartridge-specific hand-off of the form

    lea     $000006BC,a0        ; 41 F9 xx xx xx xx
    adda.l  #$00880000,a0       ; D1 FC 00 88 00 00
    jmp     (a0)                ; 4E D0

We decode that immediate and emit it as MARS_APP_ENTRY so the build can place
the application entry point exactly where the donor block already jumps,
instead of editing the block and risking the security check.

Usage:
    extract_mars_init.py <donor.32x> <out.bin> <out.inc>
"""

import sys

BLOCK_START = 0x3F0
SEARCH_END = 0x600

# lea $imm32,a0 / adda.l #$00880000,a0 / jmp (a0)
LEA_A0 = bytes((0x41, 0xF9))
ADDA_TAIL = bytes((0xD1, 0xFC, 0x00, 0x88, 0x00, 0x00, 0x4E, 0xD0))


def main(argv):
    if len(argv) != 4:
        sys.exit(__doc__)
    donor, out_bin, out_inc = argv[1:]

    with open(donor, "rb") as fh:
        rom = fh.read()

    if rom[0x100:0x108] != b"SEGA 32X":
        sys.exit(
            f"{donor}: console name at $100 is "
            f"{rom[0x100:0x110]!r}, not 'SEGA 32X'. "
            "The donor must be a 32X cartridge image."
        )

    hand_off = None
    for off in range(BLOCK_START, min(SEARCH_END, len(rom) - 14)):
        if rom[off:off + 2] == LEA_A0 and rom[off + 6:off + 14] == ADDA_TAIL:
            hand_off = off
            break

    if hand_off is None:
        sys.exit(
            f"{donor}: could not find the 'lea imm32,a0 / adda.l #$880000,a0 / "
            f"jmp (a0)' hand-off in $%04X-$%04X. This donor uses a different "
            "initial-program variant; extend this tool rather than guessing a "
            "block length." % (BLOCK_START, SEARCH_END)
        )

    entry = int.from_bytes(rom[hand_off + 2:hand_off + 6], "big")
    block_end = hand_off + 14
    block = rom[BLOCK_START:block_end]

    with open(out_bin, "wb") as fh:
        fh.write(block)

    with open(out_inc, "w") as fh:
        fh.write(
            "; Generated by tools/extract_mars_init.py -- do not edit.\n"
            "; Source: %s\n"
            "; Sega initial program block: cartridge $%04X-$%04X (%d bytes).\n"
            "; The block hands off with 'jmp' to cartridge offset $%06X.\n"
            "MARS_APP_ENTRY  equ $%06X\n"
            "MARS_INIT_SIZE  equ %d\n"
            % (donor, BLOCK_START, block_end - 1, len(block), entry, entry, len(block))
        )

    print(
        "extracted %d bytes from %s ($%04X-$%04X); application entry $%06X"
        % (len(block), donor, BLOCK_START, block_end - 1, entry)
    )
    if entry < block_end:
        sys.exit(
            "entry $%06X falls inside the security block ($%04X-$%04X); "
            "the build cannot place code there" % (entry, BLOCK_START, block_end - 1)
        )


if __name__ == "__main__":
    main(sys.argv)
